basic_settings:
  site_title: Mapa de Panes Venezolanos
  main_title: Panes Venezolanos
  site_owner: Alexander A. Ramírez M. y Jesús Enrique Méndez A.
  favicon_image: /images/logo_favicon.png
  mapsiteurl: https://panesvenezolanos.com

whatsapp:
  group1_link: 'https://chat.whatsapp.com/GrnANlWQiTvJaRFvrbhvjo'
  group1_qr: '/images/group1_qr_whatsapp.jpg'

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Panes'
      url: '/'
    - title: 'Mapa'
      url: '/mapa/'
    - title: 'Libros'
      url: '/libros/'
    - title: 'Calculadoras'
      url: '/calculadoras'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Comunidad'
      url: '/comunidad/'
    - title: 'Acerca'
      url: '/acerca'

footer_settings:
  footer_tagline: La Referencia sobre Panes Venezolanos para Panaderos Caseros.

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 20
  content_alignment: bottom

contact_settings:
  form_action: ''
  confirmation_url: '/gracias'
  email_subject: 'Email'
  send_button_text: 'Enviar'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url_1: 'https://www.instagram.com/hazpanencasa/'
  instagram_url_2: 'https://www.instagram.com/1painalafois/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#4ecdc4'
  border_color: '#dddddd'
  overlay_background_color: '#4ecdc4'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Poppins:300,500" rel="stylesheet">'
  title_font: '"Poppins", sans-serif'
  body_font: '"Poppins", sans-serif'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 14
    large_size: 15
    weight: 500
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 24
    large_size: 28
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 13
    medium_size: 15
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: G-HRV9P3H4F9
  custom_styles: ""
  header_js: ""
  footer_js: ""